### ISSUE TITLE
uindows で使った場合に、キャッシュディレクトリーが見当たらない

### ISSUE THREAD

**Issue by mike-neck** [mike-neck/ui_shig-cli#1]
現象
---

- uindows でキャッシュコマンドを実行した際に、キャッシュディレクトリーが見当たらない

ツイート
---

https://x.com/shuntia_en/status/1816969644990931303

![image](https://github.com/user-attachments/assets/a02fcbec-541a-4d03-b4e2-3ade11893106)

**Comment by mike-neck** [comment]
https://x.com/shuntia_en/status/1816988687835803705

**Comment by shuntia** [comment]
![image](https://github.com/user-attachments/assets/e1c01dce-9f7e-40d6-b106-aba512b6759e)
total 0 cache files processedと書いてあるので書き込みに失敗したか、エラーメッセージがきえてるか…？
